spring:
    application:
        name: Instalogram
    thymeleaf:
        cache: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/instalogram
        username: root
        password: ${mysql.password}
    mvc:
        static-path-pattern: /static/**
    config:
        import: security-variable.yml

mybatis:
    mapper-locations: mappers/*Mapper.xml